this:  Query {
    _mongooseOptions: {},
    _transforms: [],
    _hooks: Kareem { _pres: Map(0) {}, _posts: Map(0) {} },
    _executionCount: 1,
    mongooseCollection: NativeCollection {
      collection: Collection { s: [Object] },
      Promise: [Function: Promise],
      _closed: false,
      opts: {
        autoIndex: true,
        autoCreate: undefined,
        schemaUserProvidedOptions: [Object],
        capped: false,
        Promise: [Function: Promise],
        '$wasForceClosed': undefined
      },
      name: 'categories',
      collectionName: 'categories',
      conn: NativeConnection {
        base: [Mongoose],
        collections: [Object],
        models: [Object],
        config: [Object],
        replica: false,
        options: null,
        otherDbs: [],
        relatedDbs: {},
        states: [Object: null prototype],
        _readyState: 1,
        _closeCalled: false,
        _hasOpened: true,
        plugins: [],
        id: 0,
        _queue: [],
        _listening: false,
        _connectionString: 'mongodb+srv://forza11879:xQJtb9ooQKGUA6Ik@cluster0.veerx.mongodb.net/ecommerce?retryWrites=true&w=majority',
        _connectionOptions: [Object],
        client: [MongoClient],
        '$initialConnection': [Promise],
        name: 'ecommerce',
        host: 'cluster0-shard-00-02.veerx.mongodb.net',
        port: 27017,
        user: 'forza11879',
        pass: 'xQJtb9ooQKGUA6Ik',
        db: [Db]
      },
      queue: [],
      buffer: false,
      emitter: EventEmitter {
        _events: [Object: null prototype] {},
        _eventsCount: 0,
        _maxListeners: undefined,
        [Symbol(kCapture)]: false
      }
    },
    model: Model { Category },
    schema: Schema {
      obj: { name: [Object], slug: [Object] },
      paths: {
        name: [SchemaString],
        slug: [SchemaString],
        _id: [ObjectId],
        updatedAt: [SchemaDate],
        createdAt: [SchemaDate],
        __v: [SchemaNumber]
      },
      aliases: {},
      subpaths: {},
      virtuals: { id: [VirtualType] },
      singleNestedPaths: {},
      nested: {},
      inherits: {},
      callQueue: [],
      _indexes: [],
      methods: { initializeTimestamps: [Function (anonymous)] },
      methodOptions: {},
      statics: { avgRating: [AsyncFunction (anonymous)] },
      tree: {
        name: [Object],
        slug: [Object],
        _id: [Object],
        updatedAt: [Function: Date],
        createdAt: [Function: Date],
        __v: [Function: Number],
        id: [VirtualType]
      },
      query: {},
      childSchemas: [],
      plugins: [ [Object], [Object], [Object], [Object], [Object], [Object] ],
      '$id': 3,
      s: { hooks: [Kareem] },
      _userProvidedOptions: { timestamps: true },
      options: {
        timestamps: true,
        typePojoToMixed: true,
        typeKey: 'type',
        id: true,
        noVirtualId: false,
        _id: true,
        noId: false,
        validateBeforeSave: true,
        read: null,
        shardKey: null,
        autoIndex: null,
        minimize: true,
        discriminatorKey: '__t',
        optimisticConcurrency: false,
        versionKey: '__v',
        capped: false,
        bufferCommands: true,
        strictQuery: false,
        strict: true,
        pluralization: true
      },
      '$timestamps': { createdAt: 'createdAt', updatedAt: 'updatedAt' },
      '$globalPluginsApplied': true,
      _requiredpaths: [ 'name' ]
    },
    op: 'findOneAndDelete',
    options: {},
    _conditions: { slug: 'bmw' },
    _fields: undefined,
    _update: undefined,
    _path: undefined,
    _distinct: undefined,
    _collection: NodeCollection {
      collection: NativeCollection {
        collection: [Collection],
        Promise: [Function: Promise],
        _closed: false,
        opts: [Object],
        name: 'categories',
        collectionName: 'categories',
        conn: [NativeConnection],
        queue: [],
        buffer: false,
        emitter: [EventEmitter]
      },
      collectionName: 'categories'
    },
    _traceFunction: undefined,
    '$useProjection': true,
    _error: null
  }